
site_name: Humanities Data Benchmark

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - toc.integrate
    - search.suggest
    - search.highlight

nav:
  - Home: index.md
  - Tests: 
    - tests.md
    - T01: tests/T01.md
    - T02: tests/T02.md
    - T03: tests/T03.md
    - T04: tests/T04.md
    - T05: tests/T05.md
    - T06: tests/T06.md
    - T07: tests/T07.md
    - T08: tests/T08.md
    - T09: tests/T09.md
    - T10: tests/T10.md
    - T11: tests/T11.md
    - T12: tests/T12.md
    - T13: tests/T13.md
    - T14: tests/T14.md
    - T15: tests/T15.md
    - T16: tests/T16.md
    - T17: tests/T17.md
    - T18: tests/T18.md
    - T19: tests/T19.md
    - T20: tests/T20.md
    - T21: tests/T21.md
    - T22: tests/T22.md
    - T23: tests/T23.md
    - T24: tests/T24.md
    - T25: tests/T25.md
    - T26: tests/T26.md
    - T27: tests/T27.md
    - T28: tests/T28.md
    - T29: tests/T29.md
    - T30: tests/T30.md
    - T31: tests/T31.md
    - T32: tests/T32.md
    - T33: tests/T33.md
    - T34: tests/T34.md
    - T35: tests/T35.md
    - T36: tests/T36.md
    - T37: tests/T37.md
    - T38: tests/T38.md
    - T39: tests/T39.md
    - T40: tests/T40.md
    - T41: tests/T41.md
    - T42: tests/T42.md
    - T43: tests/T43.md
    - T44: tests/T44.md
    - T45: tests/T45.md
    - T46: tests/T46.md
    - T47: tests/T47.md
    - T48: tests/T48.md
    - T49: tests/T49.md
    - T50: tests/T50.md
    - T51: tests/T51.md
    - T52: tests/T52.md
    - T53: tests/T53.md
    - T54: tests/T54.md
    - T55: tests/T55.md
    - T56: tests/T56.md
    - T57: tests/T57.md
    - T58: tests/T58.md
    - T59: tests/T59.md
    - T60: tests/T60.md
    - T61: tests/T61.md
    - T62: tests/T62.md
    - T63: tests/T63.md
    - T64: tests/T64.md
    - T65: tests/T65.md
    - T66: tests/T66.md
    - T67: tests/T67.md
    - T68: tests/T68.md
    - T69: tests/T69.md
    - T70: tests/T70.md
    - T71: tests/T71.md
    - T72: tests/T72.md
    - T73: tests/T73.md
    - T74: tests/T74.md
    - T75: tests/T75.md
    - T76: tests/T76.md
    - T77: tests/T77.md
    - T78: tests/T78.md
    - T79: tests/T79.md
    - T80: tests/T80.md
    - T81: tests/T81.md
    - T82: tests/T82.md
    - T83: tests/T83.md
    - T84: tests/T84.md
    - T85: tests/T85.md
    - T86: tests/T86.md
    - T87: tests/T87.md
    - T88: tests/T88.md
    - T89: tests/T89.md
    - T90: tests/T90.md
    - T91: tests/T91.md
    - T92: tests/T92.md
    - T93: tests/T93.md
    - T94: tests/T94.md
    - T95: tests/T95.md
    - T96: tests/T96.md
    - T97: tests/T97.md

  - Benchmarks:
    - bibliographic_data: benchmarks/bibliographic_data.md
    - fraktur: benchmarks/fraktur.md
    - metadata_extraction: benchmarks/metadata_extraction.md
    - test_benchmark: benchmarks/test_benchmark.md
    - test_benchmark2: benchmarks/test_benchmark2.md
    - zettelkatalog: benchmarks/zettelkatalog.md
  - Archive:
    - Overview: archive/overview.md
    - 2025-05-09:
        - T22: archive/2025-05-09/T22.md
        - T79: archive/2025-05-09/T79.md
        - T80: archive/2025-05-09/T80.md
        - T81: archive/2025-05-09/T81.md
        - T82: archive/2025-05-09/T82.md
        - T83: archive/2025-05-09/T83.md
        - T84: archive/2025-05-09/T84.md
        - T85: archive/2025-05-09/T85.md
        - T86: archive/2025-05-09/T86.md
        - T87: archive/2025-05-09/T87.md
        - T88: archive/2025-05-09/T88.md
        - T89: archive/2025-05-09/T89.md
        - T90: archive/2025-05-09/T90.md
        - T91: archive/2025-05-09/T91.md
        - T92: archive/2025-05-09/T92.md
        - T93: archive/2025-05-09/T93.md
        - T94: archive/2025-05-09/T94.md
        - T95: archive/2025-05-09/T95.md
        - T96: archive/2025-05-09/T96.md
        - T97: archive/2025-05-09/T97.md
    - 2025-05-07:
        - T22: archive/2025-05-07/T22.md
        - T79: archive/2025-05-07/T79.md
        - T80: archive/2025-05-07/T80.md
        - T81: archive/2025-05-07/T81.md
        - T82: archive/2025-05-07/T82.md
        - T83: archive/2025-05-07/T83.md
        - T84: archive/2025-05-07/T84.md
        - T85: archive/2025-05-07/T85.md
        - T86: archive/2025-05-07/T86.md
        - T87: archive/2025-05-07/T87.md
        - T88: archive/2025-05-07/T88.md
        - T89: archive/2025-05-07/T89.md
        - T90: archive/2025-05-07/T90.md
        - T91: archive/2025-05-07/T91.md
        - T92: archive/2025-05-07/T92.md
        - T93: archive/2025-05-07/T93.md
        - T94: archive/2025-05-07/T94.md
        - T95: archive/2025-05-07/T95.md
        - T96: archive/2025-05-07/T96.md
        - T97: archive/2025-05-07/T97.md
    - 2025-04-17:
        - T67: archive/2025-04-17/T67.md
        - T68: archive/2025-04-17/T68.md
        - T69: archive/2025-04-17/T69.md
        - T70: archive/2025-04-17/T70.md
        - T71: archive/2025-04-17/T71.md
        - T72: archive/2025-04-17/T72.md
        - T73: archive/2025-04-17/T73.md
        - T74: archive/2025-04-17/T74.md
        - T75: archive/2025-04-17/T75.md
        - T76: archive/2025-04-17/T76.md
        - T77: archive/2025-04-17/T77.md
        - T78: archive/2025-04-17/T78.md
    - 2025-04-11:
        - T10: archive/2025-04-11/T10.md
        - T11: archive/2025-04-11/T11.md
        - T12: archive/2025-04-11/T12.md
        - T13: archive/2025-04-11/T13.md
        - T14: archive/2025-04-11/T14.md
        - T15: archive/2025-04-11/T15.md
        - T16: archive/2025-04-11/T16.md
        - T17: archive/2025-04-11/T17.md
        - T18: archive/2025-04-11/T18.md
        - T20: archive/2025-04-11/T20.md
        - T23: archive/2025-04-11/T23.md
        - T24: archive/2025-04-11/T24.md
        - T25: archive/2025-04-11/T25.md
        - T36: archive/2025-04-11/T36.md
        - T38: archive/2025-04-11/T38.md
        - T39: archive/2025-04-11/T39.md
        - T40: archive/2025-04-11/T40.md
        - T41: archive/2025-04-11/T41.md
        - T42: archive/2025-04-11/T42.md
        - T43: archive/2025-04-11/T43.md
        - T44: archive/2025-04-11/T44.md
        - T45: archive/2025-04-11/T45.md
        - T48: archive/2025-04-11/T48.md
        - T49: archive/2025-04-11/T49.md
        - T52: archive/2025-04-11/T52.md
        - T53: archive/2025-04-11/T53.md
        - T56: archive/2025-04-11/T56.md
        - T57: archive/2025-04-11/T57.md
        - T60: archive/2025-04-11/T60.md
        - T61: archive/2025-04-11/T61.md
        - T62: archive/2025-04-11/T62.md
        - T63: archive/2025-04-11/T63.md
    - 2025-04-08:
        - T07: archive/2025-04-08/T07.md
        - T08: archive/2025-04-08/T08.md
        - T09: archive/2025-04-08/T09.md
        - T26: archive/2025-04-08/T26.md
        - T27: archive/2025-04-08/T27.md
        - T29: archive/2025-04-08/T29.md
        - T30: archive/2025-04-08/T30.md
        - T31: archive/2025-04-08/T31.md
        - T33: archive/2025-04-08/T33.md
        - T35: archive/2025-04-08/T35.md
    - 2025-04-07:
        - T17: archive/2025-04-07/T17.md
        - T24: archive/2025-04-07/T24.md
        - T25: archive/2025-04-07/T25.md
    - 2025-04-02:
        - T22: archive/2025-04-02/T22.md
        - T23: archive/2025-04-02/T23.md
    - 2025-04-01:
        - T01: archive/2025-04-01/T01.md
        - T02: archive/2025-04-01/T02.md
        - T03: archive/2025-04-01/T03.md
        - T04: archive/2025-04-01/T04.md
        - T05: archive/2025-04-01/T05.md
        - T06: archive/2025-04-01/T06.md
        - T07: archive/2025-04-01/T07.md
        - T08: archive/2025-04-01/T08.md
        - T09: archive/2025-04-01/T09.md
        - T10: archive/2025-04-01/T10.md
        - T11: archive/2025-04-01/T11.md
        - T12: archive/2025-04-01/T12.md
        - T13: archive/2025-04-01/T13.md
        - T14: archive/2025-04-01/T14.md
        - T15: archive/2025-04-01/T15.md
        - T16: archive/2025-04-01/T16.md
        - T17: archive/2025-04-01/T17.md
        - T18: archive/2025-04-01/T18.md
        - T19: archive/2025-04-01/T19.md
        - T20: archive/2025-04-01/T20.md
        - T21: archive/2025-04-01/T21.md
    - 2025-03-05:
        - T01: archive/2025-03-05/T01.md
        - T02: archive/2025-03-05/T02.md
        - T03: archive/2025-03-05/T03.md
        - T04: archive/2025-03-05/T04.md
        - T05: archive/2025-03-05/T05.md
        - T06: archive/2025-03-05/T06.md
        - T07: archive/2025-03-05/T07.md
        - T08: archive/2025-03-05/T08.md
        - T09: archive/2025-03-05/T09.md
        - T10: archive/2025-03-05/T10.md
        - T11: archive/2025-03-05/T11.md
        - T12: archive/2025-03-05/T12.md
        - T13: archive/2025-03-05/T13.md
        - T14: archive/2025-03-05/T14.md
        - T15: archive/2025-03-05/T15.md
        - T16: archive/2025-03-05/T16.md
        - T17: archive/2025-03-05/T17.md
        - T18: archive/2025-03-05/T18.md
    - 2025-03-04:
        - T01: archive/2025-03-04/T01.md
        - T07: archive/2025-03-04/T07.md
    - 2025-03-02:
        - T06: archive/2025-03-02/T06.md
        - T07: archive/2025-03-02/T07.md
        - T08: archive/2025-03-02/T08.md
        - T09: archive/2025-03-02/T09.md
    - 2025-03-01:
        - T01: archive/2025-03-01/T01.md
        - T02: archive/2025-03-01/T02.md
        - T03: archive/2025-03-01/T03.md
        - T04: archive/2025-03-01/T04.md
        - T05: archive/2025-03-01/T05.md

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
