
site_name: Humanities Data Benchmark

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - toc.integrate
    - search.suggest
    - search.highlight

nav:
  - Home: index.md
  - Overview: overview.md
  - Benchmarks:
    - bibliographic_data: benchmarks/bibliographic_data.md
    - metadata_extraction: benchmarks/metadata_extraction.md
    - test_benchmark: benchmarks/test_benchmark.md
    - test_benchmark2: benchmarks/test_benchmark2.md
  - Tests:
    - 2025-02-24:
        - T1: tests/2025-02-24/T1.md
        - T2: tests/2025-02-24/T2.md
        - T3: tests/2025-02-24/T3.md
    - 2025-02-25:
        - T4: tests/2025-02-25/T4.md
    - 2025-02-28:
        - T1: tests/2025-02-28/T1.md
        - T2: tests/2025-02-28/T2.md
        - T3: tests/2025-02-28/T3.md
        - T4: tests/2025-02-28/T4.md

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
