
site_name: Humanities Data Benchmark

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - toc.integrate
    - search.suggest
    - search.highlight

nav:
  - Home: index.md
  - Tests: 
    - tests.md
    - T01: tests/T01.md
    - T02: tests/T02.md
    - T03: tests/T03.md
    - T04: tests/T04.md
    - T05: tests/T05.md
    - T06: tests/T06.md
    - T07: tests/T07.md
    - T08: tests/T08.md
    - T09: tests/T09.md
    - T10: tests/T10.md

  - Benchmarks:
    - bibliographic_data: benchmarks/bibliographic_data.md
    - metadata_extraction: benchmarks/metadata_extraction.md
    - test_benchmark: benchmarks/test_benchmark.md
    - test_benchmark2: benchmarks/test_benchmark2.md
  - Archive:
    - Overview: archive/overview.md
    - 2025-03-02:
        - T06: archive/2025-03-02/T06.md
        - T07: archive/2025-03-02/T07.md
        - T08: archive/2025-03-02/T08.md
        - T09: archive/2025-03-02/T09.md
    - 2025-03-01:
        - T01: archive/2025-03-01/T01.md
        - T02: archive/2025-03-01/T02.md
        - T03: archive/2025-03-01/T03.md
        - T04: archive/2025-03-01/T04.md
        - T05: archive/2025-03-01/T05.md

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
