name: Deploy Benchmark

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    environment: production

    steps:
      - name: Run tiny local deploy script
        run: sudo -n /usr/local/sbin/deploy_humanities_benchmark
