name: Deploy MkDocs Documentation

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install MkDocs
        run: pip install mkdocs-material

      - name: Generate Navigation
        run: |
          cd scripts
          python generate_reports.py

      - name: Deploy MkDocs
        run: mkdocs gh-deploy --force

      - name: Commit MkDocs Navigation Changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add mkdocs.yml
          git commit -m "Update navigation in MkDocs" || echo "No changes to commit"
