name: Run Benchmarks and Generate Reports

env:
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
  GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
  CLAUDE_API_KEY: ${{ secrets.CLAUDE_API_KEY }}

on:
  schedule:
    - cron: '0 0 * * 1'  # Runs every Monday at midnight UTC
  workflow_dispatch:  # Allow manual triggering


jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run benchmarks
        run: python run_benchmarks.py

      - name: Generate reports
        run: python generate_reports.py  # This script processes results

      - name: Archive previous reports
        run: |
          mkdir -p archive/$(date +'%Y-%m-%d')
          mv reports/* archive/$(date +'%Y-%m-%d')/

      - name: Commit new reports
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add reports/ archive/
          git commit -m "Updated benchmark reports for $(date +'%Y-%m-%d')" || echo "No changes to commit"
          git push

      - name: Publish reports to GitHub Pages
        run: |
           mkdir -p docs
           cp -r reports/* docs/
           git add docs/
           git commit -m "Update GitHub Pages reports for $(date +'%Y-%m-%d')" || echo "No changes to commit"
           git push